version: "3"
services:

  metabase:
    image: metabase/metabase:v0.55.4
    container_name: ${APP}_metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${MB_DBNAME}
      MB_DB_PORT: 5432
      MB_DB_USER: ${DB_UNAME}
      MB_DB_PASS: ${DB_PASS}
      MB_DB_HOST: postgres
      MB_ENCRYPTION_SECRET_KEY: ${DB_ENCRYPT_KEY}
    networks:
      - metanet1
    depends_on:
      - postgres
    restart: always
    ports:
    - ${PUBLIC_PORT}:3000

  postgres:
    image: postgres:15.13
    container_name: ${APP}_mb_postgres
    hostname: postgres
    environment:
      POSTGRES_DB: ${MB_DBNAME}
      POSTGRES_USER: ${DB_UNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - metanet1
    restart: always

networks:
  metanet1:
    driver: bridge
