# docker network create my-net
# docker volume create psql_storage
# docker-compose -f docker-compose-kc-psql-nginx.yml up -d
version: '3.7'

networks:
  proxy-net:
    external: true
  default:
    name: ${CONTAINER_NAME}-kc-net

volumes:
  psql_storage:
    external: true

services:

  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
    networks:
      - default
    ports:
      - '5437:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - psql_storage:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    networks:
      - proxy-net
      - default
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/certs/keycloak.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/certs/keycloak.key
      PROXY_ADDRESS_FORWARDING: 'true'
      # JDBC_PARAMS: 'connectTimeout=30'
    volumes:
      - ./keycloak_data:/opt/keycloak/data
      - ./certs:/opt/keycloak/conf/certs:ro
    ports:
      - ${ACCESS_PORT}:8080
    depends_on:
      - postgres
    healthcheck:
      test: curl --fail -s http://localhost:8080 || exit 1
      start_period: 30s
      interval: 15s
      timeout: 15s
      retries: 5
