version: "2"

# frontend network for resourcespace using an already existing nginx proxy for Let's Encrypt
# backend network without public accessibility for the database connection
networks:
  frontend:
    external:
      name: acme-proxy-network
  backend:

# Trying to use bind volumes directly resulted in a 500 error, but using named volumes worked  
volumes:
  mariadb:
  include:
  filestore:

services:
  resourcespace:
    image: suntorytimed/resourcespace:latest
    restart: unless-stopped
    # links resourcespace to mariadb container and makes it accessible via the URL mariadb
    depends_on:
      - mariadb-resourcespace
    volumes:
      - include:/var/www/resourcespace/include
      - filestore:/var/www/resourcespace/filestore
    # variables for setting up https via the Let's Encrypt/ACME companion
    environment:
      - HOSTNAME=dam.example.com
      - VIRTUAL_HOST=dam.example.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=dam.example.com
      - LETSENCRYPT_EMAIL=admin@example.com
    # public and private network
    networks:
      - frontend
      - backend
    # no port bind necessary due to the nginx proxy
    expose:
      - 80
  
  mariadb-resourcespace:
    image: mariadb
    restart: unless-stopped
    # env file containing the db configuration
    environment:
      - MYSQL_PASSWORD=Password1
      - MYSQL_ROOT_PASSWORD=Password1
      - MYSQL_DATABASE=resourcespace
      - MYSQL_USER=cubic
    volumes:
      - mariadb:/var/lib/mysql
    # only accesible in private network
    networks:
      - backend
