
version: '3.7'

networks:
  proxy-net:
    external: true

services:
  oauth2-proxy:
  container_name: ${CONT_NAME}-oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy
    environment:
      - OAUTH2_PROXY_PROVIDER=keycloak
      - OAUTH2_PROXY_CLIENT_ID=proxy-client
      - OAUTH2_PROXY_CLIENT_SECRET=your-client-secret
      - OAUTH2_PROXY_COOKIE_SECRET=somerandomstring
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_REDIRECT_URL=https://app.example.com/oauth2/callback
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_COOKIE_REFRESH=10m  # Refresh session every 10 minutes
      - OAUTH2_PROXY_COOKIE_EXPIRE=12h  # Session expires in 12 hours
      - OAUTH2_PROXY_COOKIE_SAMESITE=lax
      - OAUTH2_PROXY_SESSION_STORE_TYPE=cookie
      - OAUTH2_PROXY_SKIP_AUTH_ROUTES=/public
      - OAUTH2_PROXY_UPSTREAMS=http://npm
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
    ports:
      - "4180:4180"
    networks:
      - proxy-net
    restart: always
