#ctc docker stack

version: '3.5'
services:
  jsdis:
    image: mitchellday06/jsdis:${JSDIS_VERSION}
    container_name: ${JSDIS_NAME}-cubic-jsdis
    command: npm run server
    volumes:
      - "/var/jsdis/${VJSDIS_NAME}:/app"
    environment:
      APP_NAME: "${VT2_NAME} JSIDS"
    #ports:
      #- 442:443
    networks:
      - proxy-net
      - default
    restart: unless-stopped
networks:
  default:
    name: ${JSDIS_NAME}-n
